import type { FriendLink, FriendsPageConfig } from "../types/config";

// 可以在src/content/spec/friends.md中编写友链页面下方的自定义内容

// 友链页面配置
export const friendsPageConfig: FriendsPageConfig = {
	// 显示列数：2列或3列
	columns: 2,
};

// 友链配置
export const friendsConfig: FriendLink[] = [
	{
		title: "夏夜流萤",
		imgurl: "https://q1.qlogo.cn/g?b=qq&nk=7618557&s=640",
		desc: "飞萤之火自无梦的长夜亮起，绽放在终竟的明天。",
		siteurl: "https://blog.cuteleaf.cn",
		tags: ["巨佬"],
		weight: 0, // 权重，数字越大排序越靠前
		enabled: true, // 是否启用
	},
	{
      title: "GGapa",
      siteurl: "http://ggapa.net/",
      imgurl: "https://pic.imgdb.cn/item/661a28db68eb9357131fb54c.png",
      desc: "自能生羽翼，何必仰云梯",
      tags: ["朋友"],
	  weight: 0,
	  enabled: true,
    },
    {
      title: "Brilliant11001",
      siteurl: "https://www.cnblogs.com/Brilliant11001",
      imgurl: "https://cdn.luogu.com.cn/upload/usericon/602372.png",
      desc: "奋力穿过缝隙的痕迹，就是光的模样",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "HYLW",
      siteurl: "https://www.luogu.com.cn/user/663949#article",
      imgurl: "https://cdn.luogu.com.cn/upload/usericon/663949.png",
      desc: "干 一 场 硬 仗 S1",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Aventurine_stone",
      siteurl: "https://www.luogu.com.cn/user/1041101#article",
      imgurl: "https://cdn.luogu.com.cn/upload/usericon/1041101.png",
      desc: "愿人生的赌局，赢的总是我们。",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "StairsUponTemple",
      siteurl: "https://stairsupon.github.io",
      imgurl: "https://cdn.luogu.com.cn/upload/usericon/381643.png",
      desc: "Brilliant",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Lucas2011",
      siteurl: "https://lucas2011.top/",
      imgurl: "https://cdn.luogu.com.cn/upload/image_hosting/p31wgc31.png",
      desc: "无穷的远方，无数的人们，都与我有关。",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "iMaeGoo’s Blog",
      siteurl: "https://www.imaegoo.com/",
      imgurl: "https://cdn.jsdelivr.net/npm/imaegoo/avatar.jpg",
      desc: "虹墨空间站",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Mete0r’s Blog | 壹人小站",
      siteurl: "https://www.xscnas.top/",
      imgurl: "https://img.koxiuqiu.cc/imgse/23/20250428/3d98bb7a67748d08ef163bbb04c7be72.webp",
      desc: "Trust the process.",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "咖啡豆子coffee的小站",
      siteurl: "https://blog.kfdzcoffee.cn",
      imgurl: "https://images.kfdzcoffee.cn/i/1/avatar.png",
      desc: "所有奇迹的始发点",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Almango",
      siteurl: "https://www.almango.cn/",
      imgurl: "https://www.almango.cn/img/favicon.png",
      desc: "天真永不消逝，浪漫至死不渝。",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "轻笑Chuckle",
      siteurl: "https://www.qcqx.cn/",
      imgurl: "https://www.qcqx.cn/head.webp",
      desc: "漫天倾尘,风中轻笑",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "橙の小站",
      siteurl: "https://blog.zhaozilin.cn",
      imgurl: "https://thirdqq.qlogo.cn/g?b=sdk&nk=2752718571&s=640",
      desc: "靠自己，实际一些！",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "zuanshijia's blog",
      siteurl: "https://zuanshijia.top",
      imgurl: "https://zuanshijia.top/img/favicon.png",
      desc: "人要成仙,必先疯癫-分享日常,技术,业余无线电",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Jett的博客",
      siteurl: "https://jettlin.cn",
      imgurl: "http://api.jettlin.cn/api/files/1756696693415-Snipaste_2025-08-27_14-57-25.png",
      desc: "暮然回首，那人却在，灯火阑珊处",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "小元博客",
      siteurl: "https://reblog.cn",
      imgurl: "https://reblog.cn/upload/img/web-user.jpeg",
      desc: "技术分享·趣味杂谈-前端技术 日常闲谈",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "青序栈",
      siteurl: "https://qxzhan.cn/",
      imgurl: "https://qxzhan.cn/favicon.png",
      desc: "青序成栈·向简而生",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "AcoFork",
      siteurl: "https://2x.nz/",
      imgurl: "https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=0",
      desc: "Protect What You Love.",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "worable's Blog",
      siteurl: "https://worable.top/",
      imgurl: "https://www.worable.top/upload/avatar.jpg",
      desc: "≡ω≡ 嗯对，一名普通的职一牲~",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "折腾日记",
      siteurl: "https://blog.zyx-2012.cn/",
      imgurl: "https://blog.zyx-2012.cn/favicon.ico",
      desc: "专注于笔记、分享的博客",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "LYEy_isine个人博客",
      siteurl: "https://caiyifeng.top/",
      imgurl: "https://caiyifeng.top/assets/images/avatar.webp",
      desc: "花海无一日,少年踏自来",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "喵二の小博客",
      siteurl: "https://www.miaoer.net/",
      imgurl: "https://static.miaoer.net/logo/avatar.webp",
      desc: "缘，妙不可言",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Boranstars",
      siteurl: "https://blog.boranstars.top/",
      imgurl: "https://blog.boranstars.top/upload/avatar.jpg",
      desc: "分享科技与生活",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "mccsjs",
      siteurl: "https://seln.cn/",
      imgurl: "https://seln.cn/img/ico.jpg",
      desc: "点一盏灯，等一个迷路的夜🍁🍁🍁",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Xeniume",
      siteurl: "https://xeniu.me",
      imgurl: "https://xeniu.me/favicon.jpg",
      desc: "One Last Dance.",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "CcoMm",
      siteurl: "https://blog.ccomm.top",
      imgurl: "https://avatars.githubusercontent.com/u/147143261",
      desc: "你要吃C4吗？",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "TryBlog",
      siteurl: "https://halo.mctry.cn/",
      imgurl: "https://halo.mctry.cn/upload/Image_1111784543629375.jpg",
      desc: "微风晚畔，灯影初燃",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "热衷于de博客",
      siteurl: "https://zooyoo.top/",
      imgurl: "https://zooyoo.top/img/l.png",
      desc: "一个有趣的灵魂",
      tags: ["朋友"],
weight: 0,
enabled: true,
    },
    {
      title: "Elykia",
      siteurl: "https://blog.elykia.cn/",
      imgurl: "https://bu.dusays.com/2024/10/25/671b2438203a6.gif",
      desc: "致以无瑕之人",
      tags: ["朋友"],
weight: 0,
enabled: true,
    }
];

// 获取启用的友链并按权重排序
export const getEnabledFriends = (): FriendLink[] => {
	return friendsConfig
		.filter((friend) => friend.enabled)
		.sort((a, b) => b.weight - a.weight);
};
