name: 部署博客

on:
  # 每次推送到 `master` 分支时触发这个"工作流程"
  # 如果你使用了别的分支名，请按需将 `master` 替换成你的分支名
  push:
    branches: [ master ]
  # 允许你在 GitHub 上的 Actions 标签中手动触发此"工作流程"
  workflow_dispatch:

jobs:
  blog-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Optimize database
        run: rm -f .astro/content.db .astro/content.db-wal .astro/content.db-shm

      - name: Increase inotify limits
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p 
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.4
          run_install: false
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build site
        run: |
          pnpm clean
          pnpm build

      - name: Create .nojekyll file
        run: touch dist/.nojekyll
      
      - name: Deploy to repo
        run: |
          cd dist
          git config --global credential.helper store
          git config --global init.defaultBranch master
          git config --global user.email ""
          git config --global user.name ""
          git config user.password ""
          git init
          git add .
          git commit -m 'Site Auto-update'
          git push 
